
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aa?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true


